-- RESTAURANTS TABLE
CREATE TABLE RESTAURANTS (
    RESTAURANT_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    CUISINE_TYPE VARCHAR(50) NOT NULL
);

--DRIVERS TABLE
CREATE TABLE DRIVERS (
    DRIVER_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    PHONE VARCHAR(15) UNIQUE NOT NULL,
    VEHICLE_TYPE VARCHAR(50) NOT NULL,
    JOIN_DATE DATE NOT NULL
);


-- MENU TABLE
CREATE TABLE MENU (
    MENU_ID INT PRIMARY KEY AUTO_INCREMENT,
    RESTAURANT_ID INT NOT NULL,
    DISH_NAME VARCHAR(100) NOT NULL,
    PRICE DECIMAL(8,2) NOT NULL CHECK (PRICE > 0),
    CATEGORY ENUM('MAIN COURSE', 'DESSERT', 'BEVERAGE', 'STARTER') NOT NULL,
    FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS(RESTAURANT_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- CUSTOMERS TABLE
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    PHONE VARCHAR(15) UNIQUE NOT NULL,
    CITY VARCHAR(50),
    JOIN_DATE DATE NOT NULL
);

-- ORDERS TABLE
CREATE TABLE ORDERS (
    ORDER_ID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_ID INT NOT NULL,
    RESTAURANT_ID INT NOT NULL,
    ORDER_DATE DATE NOT NULL,
    DELIVERY_TIME_MINUTES INT,
    DRIVER_ID INT,
    PAYMENT_MODE ENUM('UPI', 'CARD', 'CASH') NOT NULL,

    -- FOREIGN KEYS
    CONSTRAINT FK_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
    CONSTRAINT FK_RESTAURANT FOREIGN KEY (RESTAURANT_ID) REFERENCES RESTAURANTS(RESTAURANT_ID),
    CONSTRAINT FK_DRIVER FOREIGN KEY (DRIVER_ID) REFERENCES DRIVERS(DRIVER_ID)
);

--ORDER_DETAILS TABLE
CREATE TABLE ORDER_DETAILS (
    ORDER_DETAIL_ID INT PRIMARY KEY AUTO_INCREMENT,
    ORDER_ID INT NOT NULL,
    MENU_ID INT NOT NULL,
    QUANTITY INT NOT NULL CHECK (QUANTITY > 0),

    CONSTRAINT FK_ORDER FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT FK_MENU FOREIGN KEY (MENU_ID) REFERENCES MENU(MENU_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

--REVIEWS TABLE

CREATE TABLE REVIEWS (
    REVIEW_ID INT PRIMARY KEY AUTO_INCREMENT,
    ORDER_ID INT NOT NULL,
    CUSTOMER_ID INT NOT NULL,
    RESTAURANT_ID INT NOT NULL,
    RATING INT CHECK (RATING BETWEEN 1 AND 5),
    REVIEW_TEXT TEXT,

    CONSTRAINT FK_REVIEW_ORDER FOREIGN KEY (ORDER_ID) 
        REFERENCES ORDERS(ORDER_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT FK_REVIEW_CUSTOMER FOREIGN KEY (CUSTOMER_ID) 
        REFERENCES CUSTOMERS(CUSTOMER_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,

    CONSTRAINT FK_REVIEW_RESTAURANT FOREIGN KEY (RESTAURANT_ID) 
        REFERENCES RESTAURANTS(RESTAURANT_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

